### ISSUE TITLE
vocab.json

### ISSUE THREAD

**Issue by bazyliszek** [yiqunchen/GenePT#1]
Is it possible to upload missing vocab.json? I do not see where it its created.  Thank you. By the way, aorta_data_analysis.ipyng works great. Just costed 3 dollars.

**Comment by yiqunchen** [comment]
Thanks! Feel free to let us know if you wanna see additional analysis in cell-levels; we are also planning to release the precomputed GPT embeddings of the sampled cells.

The initial list of genes are curated from [vocab.json](https://drive.google.com/drive/folders/1oWh_-ZRdhtoGQ2Fw24HP41FgLoomVo-y) (provided by the scGPT authors) and [token_dictionary.pkl](https://huggingface.co/ctheodoris/Geneformer/blob/main/geneformer/token_dictionary.pkl) (provided by the Geneformer authors).

**Comment by bazyliszek** [comment]
Thank you for these files. It was easier to replicate this now. I will think about additional analysis in cell-levels.

**Comment by zb051207** [comment]
If there's no issue with my operation, the author of Geneformer has deleted the token_dictionary.pkl file. I want to reproduce the experimental results using this file. Do you have a saved copy?
