### ISSUE TITLE
Request: adding sample `NCBI_cleaned_summary_of_genes.json`

### ISSUE THREAD

**Issue by jamesbraza** [yiqunchen/GenePT#2]
Hello! Working on trying these methods posed here out now.

Looking at [https://github.com/yiqunchen/GenePT/blob/383c550e6e29492a8d48b160eb39c1a129bb6d70/gene_embeddings_examples.ipynb](https://github.com/yiqunchen/GenePT/blob/383c550e6e29492a8d48b160eb39c1a129bb6d70/gene_embeddings_examples.ipynb)'s cell 3, it reads in a `NCBI_cleaned_summary_of_genes.json`.

Any chance you can add either the full, or just a subset of this JSON file? That way I can have a reference of what yours looked like.

**Comment by yiqunchen** [comment]
Thank you for your interest in our paper! The json file is now deposited on https://zenodo.org/records/10030426; please let me know if you have any additional questions :)

**Comment by jamesbraza** [comment]
Thank you @yiqunchen!

One comment is it looks like your `.zip` addition has some `__MACOSX` metadata, maybe repost the `.zip` file without that extra `__MACOSX` metadata inside:

> ![screenshot of macOS metadata](https://github.com/yiqunchen/GenePT/assets/8990777/b6b181af-b300-475c-9dbc-6cb992548798)

**Comment by HelloWorldLTY** [comment]
Hi, I have a following bug observation in the same ipynb file, that is:

```
with open(f"{data_dir}GPT_3_5_gene_embeddings.pickle", "wb") as fp:
    pickle.dump(gpt_gene_name_to_embedding_clean_text, fp)
```

It seems that this ipynb file does not include the package "pickle", so I think we may need to do "import pickle" before running this code, is it correct? Thanks.
