### ISSUE TITLE
Request: demo notebook for `scanpy`/matmul aspect of Methods 3.1

### ISSUE THREAD

**Issue by jamesbraza** [yiqunchen/GenePT#3]
In the paper's Methods section 3.1, paragraph 2, it talks about using `scanpy` and then doing matrix multiplication with embeddings.

Any chance you'd be willing to add an IPython notebook showing how `scanpy` and the matrix multiplication logic were implemented?

It really helps me to read Python code at the same time as reading the Methods section. Thank you in advance

**Comment by yiqunchen** [comment]
Thanks for your great question! We have now updated the `aorta_data_analysis` notebook to show how we can get GenePT-w embeddings from a simple numpy matrix multiplication (to reproduce the example w/o having the compute the gene embeddings yourself, one can use the precomputed pkl files deposited at https://zenodo.org/records/10030426). 

Please let me know if you have additional questions!

**Comment by jamesbraza** [comment]
Thank you @yiqunchen ! Going to close this out, will reopen another issue if I encounter something else.  Cheers!
